# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


title           : Dr. Person
subtitle        : Subtitle
phone           : (555) 555-5555
functionalPhone : "555555555"
email           : person@example.com #this is also the email contact forms will go to
author          : Dr. Person
# formspree_form_path: moqpykav
# logo:     #optional, defaults to site title
  # path: assets\img\logo.webp
  # height: 60 #height in px, defaults to 52px

google:
  #analytics:  #Google Analytics tracking code here
  #ads: 
  #tagmanager: 

sass:
    style: compressed

collections:
  services:
    layout: service
    output: true
    permalink: /:name

markdown: kramdown

plugins:
  - jekyll-remote-theme